# 游戏常量
SCREEN_WIDTH: 800
SCREEN_HEIGHT: 480
BLOCK_SIZE: 20
PLAYFIELD_WIDTH: 32
PLAYFIELD_HEIGHT: 24
SCOREBOARD_WIDTH: 150
SCOREBOARD_HEIGHT: 250
FPS: 60
INIT_SPEED: 100   # ms
HARD_DROP_SPEED: 10
LEVEL: 0
SNAKE_IDX: 1
FOOD_IDX: 2
COLOR: ((30, 40, 255), (100, 150, 166))